In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)
print(a.size)
print(a.shape)
print(a.ndim) # 维数
print(a.dtype)

[1 2 3]
3
(3,)
1
int32


In [3]:
a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
a.dtype

dtype('float32')

In [4]:
a.reshape(3, 2)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float32)

In [5]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0, 10, 10, endpoint=False) # 等差数列 其中0-10,取10个数，endpoint表示不包括10

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [8]:
np.logspace(0, 10, 10, endpoint=False, base=2) # 等比数列

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [9]:
2**np.linspace(0, 10, 10, endpoint=False)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [10]:
np.zeros((2, 3)) # 全0数组

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.diag([4, 3, 2, 1]) # 对角线数组

array([[4, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 1]])

In [13]:
np.ones((3,3)) # 全1数组，二维用元组

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.ones(3) # 一维直接单个数

array([1., 1., 1.])

In [15]:
a = np.array([1, 2, 3], dtype=np.int8)
a.dtype

dtype('int8')

In [16]:
b = np.int32(a) # 数据类型转换
b.dtype

dtype('int32')

In [17]:
# 生成随机数
np.random.random(size=6) # 0~1之间

array([0.37480121, 0.83433122, 0.5261414 , 0.39961098, 0.0522445 ,
       0.28828741])

In [18]:
np.random.rand(3, 2, 2) # 3行 2列 2纬度

array([[[0.22349724, 0.1527039 ],
        [0.78168346, 0.70959809]],

       [[0.70158358, 0.49858742],
        [0.8219042 , 0.34944664]],

       [[0.02305529, 0.79213976],
        [0.83550905, 0.03654787]]])

In [19]:
np.random.randn(2, 3, 2) # 标准正太分布

array([[[-1.56234178,  1.90604747],
        [-2.92987229,  0.39907849],
        [ 0.80603118,  0.06271834]],

       [[-1.66603628,  0.57650512],
        [-0.91118242, -0.62167164],
        [-0.26467641, -0.69422678]]])

In [20]:
np.random.randint(0, 10, size=(3, 2)) # 0~10内，3行2列的随机数

array([[9, 9],
       [7, 8],
       [0, 0]])

In [21]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr[1:, 1:]

array([[5, 6],
       [8, 9]])

In [22]:
arr[1,2]

6

In [23]:
arr[:, 2] # 第二列元素

array([3, 6, 9])

In [24]:
# 展平数组
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr.flatten() # 横向展平

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr.flatten('F') # 纵向展平

array([1, 4, 7, 2, 5, 8, 3, 6, 9])

In [27]:
a = np.arange(10).reshape(2, 5)
b = np.linspace(0, 1, endpoint=False, num=10).reshape(2,5) # 等差数列 0~1，取num10个数，endpoint不包括1

In [28]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [29]:
b

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [30]:
np.vstack((a, b)) # 纵向组合
np.concatenate((a, b), axis=0) # 同上效果

array([[0. , 1. , 2. , 3. , 4. ],
       [5. , 6. , 7. , 8. , 9. ],
       [0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9]])

In [31]:
np.hstack((a, b)) # 横向组合
np.concatenate((a, b), axis=1) # 同上效果

array([[0. , 1. , 2. , 3. , 4. , 0. , 0.1, 0.2, 0.3, 0.4],
       [5. , 6. , 7. , 8. , 9. , 0.5, 0.6, 0.7, 0.8, 0.9]])

In [32]:
c = np.array([1,2,3,4,5,6])
np.hsplit(c, 2) # 横向切割

[array([1, 2, 3]), array([4, 5, 6])]

In [33]:
d = np.arange(9).reshape(3, 3)
print(d)
np.split(d, 3, axis=0) # 纵向切割

[[0 1 2]
 [3 4 5]
 [6 7 8]]


[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [35]:
np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

In [40]:
a = np.mat([[1, 2], [3, 4]])
a

matrix([[1, 2],
        [3, 4]])

In [43]:
b = np.matrix([[5, 6], [7, 8]])
b

matrix([[5, 6],
        [7, 8]])

In [44]:
np.bmat('a b;b a') # 拼接矩阵

matrix([[1, 2, 5, 6],
        [3, 4, 7, 8],
        [5, 6, 1, 2],
        [7, 8, 3, 4]])

In [45]:
matrix1 = np.mat("1 2 3;4 5 6;7 8 9")
matrix1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [46]:
matrix2 = np.matrix([[123],[456],[789]])
matrix2

matrix([[123],
        [456],
        [789]])

In [47]:
a = [[1, 2], [3, 4]]
b = [[1, 1], [1, 1]]
np.array(a) * np.array(b)

array([[1, 2],
       [3, 4]])

In [49]:
print(np.matrix(a))
print(np.matrix(b))
np.matrix(a) * np.matrix(b)

[[1 2]
 [3 4]]
[[1 1]
 [1 1]]


matrix([[3, 3],
        [7, 7]])

In [50]:
np.array(a).dot(np.array(b)) # dot()点乘，效果同 矩阵*

array([[3, 3],
       [7, 7]])

In [51]:
np.multiply(np.matrix(a), np.matrix(b)) # 矩阵对应元素相乘

matrix([[1, 2],
        [3, 4]])

In [58]:
print(np.matrix(a))
np.matrix(a).T # 转置

[[1 2]
 [3 4]]


matrix([[1, 3],
        [2, 4]])

In [59]:
x = np.array([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
y = np.array([[1, 2, 3]])
x + y

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [60]:
z = np.array([[1], [2], [3]])
x + z

array([[1, 1, 1],
       [3, 3, 3],
       [5, 5, 5]])

In [61]:
a = [[0]*3]
a

[[0, 0, 0]]